name: Build project after push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: ffmpeg setup
        uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Encode videos to H.264 + AAC
        run: |
          mkdir -p encoded_videos
          for f in app/src/main/assets/video/*.mp4; do
            filename=$(basename "$f")
            ffmpeg -i "$f" -c:v libx264 -preset fast -crf 23 -c:a aac -b:a 128k "encoded_videos/$filename"
          done
          cp encoded_videos/* app/src/main/assets/video/

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean build
        run: ./gradlew clean

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace --no-build-cache

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v5
        with:
          name: shortvideo-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
